# Generated by Django 3.1.4 on 2020-12-08 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplo_1',
            fields=[
                ('campo_ejemplo1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('campo_ejemplo2', models.CharField(max_length=100)),
                ('campo_ejemplo3', models.CharField(max_length=100)),
                ('campo_ejemplo4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ejemplo_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_ejemplo2', models.CharField(max_length=100)),
                ('campo_ejemplo3', models.CharField(max_length=100)),
                ('campo_ejemplo4', models.CharField(max_length=100)),
                ('campo_ejemplo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_DB.ejemplo_1')),
            ],
        ),
    ]
